# Generated by Django 6.0.6 on 2026-07-03 05:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('enabled_vendors', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CorrelationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('complete', 'Complete'), ('partial', 'Partial (some vendors failed)'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('stale_days', models.PositiveIntegerField(default=14)),
                ('vendor_status', models.JSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='dashboard.client')),
            ],
            options={
                'ordering': ['-started_at'],
                'get_latest_by': 'started_at',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_key', models.CharField(db_index=True, max_length=255)),
                ('hostname', models.CharField(max_length=255)),
                ('os', models.CharField(blank=True, max_length=255)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='dashboard.client')),
            ],
            options={
                'ordering': ['join_key'],
            },
        ),
        migrations.CreateModel(
            name='CoverageSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('covered', 'Covered'), ('missing_agent', 'Missing agent'), ('orphaned_agent', 'Orphaned agent'), ('stale_coverage', 'Stale coverage')], db_index=True, max_length=32)),
                ('vendor', models.CharField(blank=True, max_length=32)),
                ('match_method', models.CharField(blank=True, max_length=32)),
                ('agent_last_seen', models.DateTimeField(blank=True, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='dashboard.correlationrun')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='dashboard.device')),
            ],
            options={
                'ordering': ['device__join_key', 'vendor'],
            },
        ),
        migrations.AddConstraint(
            model_name='device',
            constraint=models.UniqueConstraint(fields=('client', 'join_key'), name='uniq_device_per_client'),
        ),
        migrations.AddIndex(
            model_name='coveragesnapshot',
            index=models.Index(fields=['run', 'status'], name='dashboard_c_run_id_f1efb9_idx'),
        ),
    ]
