# Generated by Django 6.0.6 on 2026-07-04 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragesnapshot',
            name='machine_type',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='coveragesnapshot',
            name='platform',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
