# Generated by Django 6.0.6 on 2026-07-04 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_coveragesnapshot_machine_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coveragesnapshot',
            name='eol_status',
            field=models.CharField(choices=[('unknown', 'Unknown'), ('supported', 'Supported'), ('eol_soon', 'EOL soon'), ('end_of_life', 'End of life')], default='unknown', max_length=16),
        ),
        migrations.AddField(
            model_name='coveragesnapshot',
            name='os_build',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
