# Generated by Django 6.0.6 on 2026-07-04 06:33

import dashboard.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_coveragesnapshot_eol_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='ad_target_device',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='client',
            name='sync_interval_hours',
            field=models.PositiveIntegerField(default=24),
        ),
        migrations.CreateModel(
            name='VendorCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('bitdefender', 'bitdefender'), ('carbonblack', 'carbonblack'), ('sentinelone', 'sentinelone')], max_length=32)),
                ('credentials', dashboard.fields.EncryptedJSONField(blank=True, default=dict)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_credentials', to='dashboard.client')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('client__isnull', True)), fields=('vendor',), name='uniq_global_vendor_credential'), models.UniqueConstraint(condition=models.Q(('client__isnull', False)), fields=('client', 'vendor'), name='uniq_per_client_vendor_credential')],
            },
        ),
    ]
