# Generated by Django 6.0.6 on 2026-07-04 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_client_ad_target_device_client_sync_interval_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='ad_target_device',
        ),
        migrations.AddField(
            model_name='client',
            name='ad_target_devices',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
