# Generated by Django 6.0.6 on 2026-07-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_remove_client_ad_target_device_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vendorcredential',
            name='uniq_per_client_vendor_credential',
        ),
        migrations.AddField(
            model_name='vendorcredential',
            name='site_label',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddConstraint(
            model_name='vendorcredential',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', False)), fields=('client', 'vendor', 'site_label'), name='uniq_per_client_vendor_site_credential'),
        ),
    ]
