# Generated by Django 6.0.6 on 2026-07-04 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_vendorcredential_uniq_per_client_vendor_credential_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='vendorcredential',
            name='uniq_global_vendor_credential',
        ),
        migrations.AddConstraint(
            model_name='vendorcredential',
            constraint=models.UniqueConstraint(condition=models.Q(('client__isnull', True)), fields=('vendor', 'site_label'), name='uniq_global_vendor_account_credential'),
        ),
    ]
